### ISSUE TITLE
Write user stories for new build.wmo/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Mofo-Design#27]
As a <type of user>, I want <some goal> so that <some reason>.

**Comment by cassiemc** [comment]
@xmatthewx Can you knock these out today?

**Comment by cassiemc** [comment]
I'll take these on since I need them to work on the UI.

### Designers
* As a **designer**, I want to know what assets already exist so that I don't have to start from scratch every time I begin a project.
* As a **new design employee or contributor**, I'd like to know what the design process is like at Mozilla so that I can make meaningful contributions and hit the ground running.
* As a **potential Mofo employee** I'd like to know what our design process is so that I can determine if I am a good fit for the team.
* As a **designer at another organization**, I'd like to find design resources that might help us improve our own process.

### Engineers
* As an **engineer**, I'd like to know where to find design resources like logos and fonts so that I don't have to keep bugging designers.
* As an **engineer** I want to know how designers do what they do because I am interested in design and want to learn more.
 
### Product managers & drivers
* As a **product manager**, I want to know what the design team process is so that I can make the best use of the design resources available to me.
* As a **product owner or driver**, I'd like to know where I can find design resources to help move the process along.
* As a **product owner or driver**, I'd like to know how to engage with designers better to get the resources and results that I need.
* As a **Mofo employee**, I'd like to know what kinds of work we can engage in with designers so I know what's available to me and can potentially think outside the box about what we need.

### Contributors
* As a **design contributor**, I'd like to know what bugs are available for me to work on so that I can get started easily and make meaningful contributions.
* As a **design contributor**, I'd like to know how to get started.
* As **any of the people above** I want to know how to get help if I'm stuck.

@xmatthewx @flukeout @sabrinang @lovegushwa R? –  am I missing anything major?

**Comment by cassiemc** [comment]
@flukeout R? please? I'd like to close today if possible!

**Comment by flukeout** [comment]
Looks great, a few additions listed below for your considerations.

* As a **designer**, I'd like to know where to find design resources like logos and fonts so that I don't have to keep bugging the other designers (same as engineer point).
* As a **designer**, I'd like to find templates and examples of different types of design products to help me work faster and create consistent, on-brand work.
* As **any of the people above** I'd like to learn about the individual members of the design team, their areas of interest and expertise and how to reach out to them if I want help or guidance.

**Comment by cassiemc** [comment]
Nice ones, thanks @flukeout! Will add to the list above and close unless you have any other concerns.

**Comment by flukeout** [comment]
R+

**Comment by cassiemc** [comment]
:hand:

**Comment by flukeout** [comment]
:hammer: :clock:
