### ISSUE TITLE
Rename this repo to 'Mofo-Design'

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Mofo-Design#47]
Seems to make more sense to me. Any objections? @flukeout @xmatthewx @vazquez @sabrinang @lovegushwa

**Comment by xmatthewx** [comment]
:+1:

**Comment by cassiemc** [comment]
Aaaand done.

**Comment by xmatthewx** [comment]
Should we also drop mofo? It's redundant since this repo sits within the foundation account. It's also unintelligible to outsiders.

**Comment by vazquez** [comment]
Big +1

**Comment by vazquez** [comment]
**MozillaFoundation / Design** reads really great :sunglasses:

**Comment by cassiemc** [comment]
Nice! Will do.

**Comment by cassiemc** [comment]
Done!

**Comment by vazquez** [comment]
Yay! :tulip:
